# This workflow will build the gatsby project, then deploy it to firebase.

name: Build and deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Build Gatsby
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
